services:
  # -----------------------------
  # Nginx Gateway
  # -----------------------------
  - type: web
    name: gateway
    env: docker
    plan: free
    rootDir: ./nginx
    dockerfilePath: ./nginx/Dockerfile
    autoDeploy: true

  # -----------------------------
  # Workforce
  # -----------------------------
  - type: web
    name: workforce-backend
    env: python
    rootDir: ./services/workforce/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: workforce-frontend
    env: docker
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    autoDeploy: true

  # -----------------------------
  # Academy
  # -----------------------------
  - type: web
    name: academy-backend
    env: python
    rootDir: ./services/academy/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: academy-frontend
    env: docker
    rootDir: ./services/academy/frontend
    dockerfilePath: ./services/academy/frontend/Dockerfile
    plan: free
    autoDeploy: true
