services:
  # -----------------------------
  # Nginx Gateway
  # -----------------------------
  - type: web
    name: gateway
    env: docker
    plan: free
    rootDir: ./nginx
    dockerfilePath: ./nginx/Dockerfile
    autoDeploy: true

  # -----------------------------
  # Workforce
  # -----------------------------
  - type: web
    name: workforce-backend
    env: python
    rootDir: ./services/workforce/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: workforce-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishPath: ./dist

  # -----------------------------
  # Academy
  # -----------------------------
  - type: web
    name: academy-backend
    env: python
    rootDir: ./services/academy/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: academy-frontend
    env: static
    rootDir: ./services/academy/frontend
    buildCommand: npm install && npm run build
    publishPath: ./dist

  # -----------------------------
  # Shop
  # -----------------------------
  - type: web
    name: shop-backend
    env: python
    rootDir: ./services/shop/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: shop-frontend
    env: static
    rootDir: ./services/shop/frontend
    buildCommand: npm install && npm run build
    publishPath: ./dist
