"""Add is_pdf_approved to Topic

Revision ID: 3b9ad3f4dc78
Revises: 1574e498844f
Create Date: 2025-08-15 06:02:15.715859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9ad3f4dc78'
down_revision: Union[str, Sequence[str], None] = '1574e498844f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('is_pdf_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_pdf_approved')
    # ### end Alembic commands ###
