"""Add description to gist_centers

Revision ID: 0ae4454aa70b
Revises: 07d1eafe0271
Create Date: 2025-08-30 22:02:42.618651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae4454aa70b'
down_revision: Union[str, Sequence[str], None] = '07d1eafe0271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gist_centers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gist_centers', 'description')
    # ### end Alembic commands ###
