"""init tables

Revision ID: 899f06f400a2
Revises: 
Create Date: 2025-08-26 13:11:08.523906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899f06f400a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_index(op.f('ix_churches_name'), 'churches', ['name'], unique=True)

    # ✅ correct unique constraint for departments
    op.create_unique_constraint(
        'uq_departments_church_name',  # give the constraint a name
        'departments',
        ['church_id', 'name']
    )

    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'address')

    # ✅ drop constraint with the same name as created above
    op.drop_constraint('uq_departments_church_name', 'departments', type_='unique')

    op.drop_index(op.f('ix_churches_name'), table_name='churches')
    # ### end Alembic commands ###
